[package]
name = "dsl-macros"
description = "DSL Macros cho nghiệp vụ ngân hàng"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
core-banking = { path = "../core-banking" }
business = { path = "../business" }
